version: '3.7'

services:
  web:
    build:
        context: './config/docker/web'
        dockerfile: './Dockerfile'
    depends_on:
      - database
    ports:
      - '8080:80'
    volumes: 
      - ./server/html:/var/www/html
      - ./server/public:/var/www/html/public
      - ./server/wp-content/themes:/var/www/html/public/wp-content/themes
      - ./server/wp-content/uploads:/var/www/html/public/wp-content/uploads
      - ./server/wp-content/plugins:/var/www/html/public/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: wpdin_
    links:
      - database:mysql

  database:
    image: mariadb
    ports:
      - '8082:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./server/database:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password 
    links:
      - database:database